all:
  hosts:
    node1:
      ansible_ssh_user: ubuntu
      ansible_host: 37.152.176.159
      ip: 37.152.176.159
      access_ip: 37.152.176.159
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
